eroom/src/main/resources/templates/include/layout.html, eroom/src/main/resources/templates/index.html
=> [jhs] layout content 깨짐 해결

eroom/src/main/java/com/eroom/directory/entity/Department.java, eroom/src/main/java/com/eroom/directory/entity/Employee.java, eroom/src/main/java/com/eroom/directory/entity/Profile.java, eroom/src/main/resources/templates/include/layout.html
[ksk] entity 관련 오류 해결, layout.html 오류 해결
- spring.jpa.hibernate.ddl-auto=update 주석 처리
- layout.html <!DOCTYPE html> 수정
=> [ksk] entity 관련 오류 해결, layout.html 오류 해결

eroom/src/main/java/com/eroom/authority/dto/AuthorityDto.java, eroom/src/main/java/com/eroom/authority/dto/AuthorityMappingDto.java, eroom/src/main/java/com/eroom/authority/dto/AuthorityMenuDto.java, eroom/src/main/java/com/eroom/authority/dto/AuthorityMenuMappingDto.java, eroom/src/main/java/com/eroom/authority/entity/Authority.java, eroom/src/main/java/com/eroom/authority/entity/AuthorityMapping.java, eroom/src/main/java/com/eroom/authority/entity/AuthorityMenu.java, eroom/src/main/java/com/eroom/authority/entity/AuthorityMenuMapping.java, eroom/src/main/java/com/eroom/directory/dto/DepartmentDto.java, eroom/src/main/java/com/eroom/directory/dto/EmployeeDirectoryDto.java, eroom/src/main/java/com/eroom/directory/dto/EmployeeDto.java, eroom/src/main/java/com/eroom/directory/dto/ProfileDto.java, eroom/src/main/java/com/eroom/directory/dto/TeamDto.java, eroom/src/main/java/com/eroom/directory/entity/DirectoryMemo.java, eroom/src/main/java/com/eroom/directory/entity/Employee.java, eroom/src/main/java/com/eroom/directory/entity/EmployeeDirectory.java, eroom/src/main/java/com/eroom/directory/entity/PartnerDirectory.java, eroom/src/main/resources/templates/directory/list.html
[ksk] employee, authority 관련 Entity, Dto 작성중.
- Entity, Dto 작성 완료
- toEntity, toDto 메소드 작성중
=> [ksk] employee, authority 관련 Entity, Dto 작성중.

eroom/src/main/java/com/eroom/directory/entity/Employee.java, eroom/src/main/java/com/eroom/directory/entity/Profile.java, eroom/src/main/java/com/eroom/login/controller/LoginController.java, eroom/src/main/java/com/eroom/login/repository/EmployeeRepository.java, eroom/src/main/java/com/eroom/login/service/EmployeeService.java, eroom/src/main/java/com/eroom/security/EmployeeDetails.java, eroom/src/main/java/com/eroom/security/EmployeeDetailsService.java, eroom/src/main/resources/templates/include/layout.html, eroom/src/main/resources/templates/login.html
=> [jhs] security login 1차 완료

eroom/src/main/java/com/eroom/drive/contorller/DriveController.java, eroom/src/main/resources/templates/drive/company.html, eroom/src/main/resources/templates/drive/department.html, eroom/src/main/resources/templates/drive/personal.html, eroom/src/main/resources/templates/drive/team.html
[lyj] 드라이브 작성중
- 회사,팀,부서,개인 페이지 이동완료
- 회사,팀,부서,개인 페이지 부트스트랩적용
=> Ly j드라이브 작성중 	

eroom/src/main/resources/templates/include/nav.html, eroom/src/main/resources/templates/mail/list.html
=> [kty] nav 어노테이션 적용

eroom/src/main/java/com/eroom/mail/contorller/MailController.java, eroom/src/main/java/com/eroom/mail/dto/MailDto.java, eroom/src/main/java/com/eroom/mail/dto/MailReceiverDto.java, eroom/src/main/java/com/eroom/mail/entity/Mail.java, eroom/src/main/resources/templates/include/nav.html, eroom/src/main/resources/templates/mail/list.html, eroom/src/main/resources/templates/mail/mailCreate.html, eroom/src/main/resources/templates/mail/mailReceiverCc.html, eroom/src/main/resources/templates/mail/mailReceiverTo.html, eroom/src/main/resources/templates/mail/mailSent.html
어노테이션 경로 변경
/mail/receiverTo >  /mail/sent 보낸 사람
/mail/receiverCc 삭제 > /mail/receiverTo 받는 사람 컨셉으로 수정
=> Kty nav 추가 수정

eroom/src/main/java/com/eroom/attendance/controller/AttendanceController.java, eroom/src/main/resources/templates/admin/employeeManagement.html, eroom/src/main/resources/templates/admin/meetingroom.html, eroom/src/main/resources/templates/admin/sleep.html, eroom/src/main/resources/templates/admin/vehicle.html, eroom/src/main/resources/templates/attendance/list.html, eroom/src/main/resources/templates/checkinout.html, eroom/src/main/resources/templates/mypage/list.html
- 관리자 페이지 : 회의실, 차량, 숙직실, 회원관리 페이지 부트스트랩 적용 / 등록 버튼 모달 반영, 목록 테이블 구성 완료
- 출퇴근 카드 생성 -> 차후 home.html에 들어갈 출퇴근 카드. 임시로 templates아래 checkinout.html 생성 해놓음.
=> [cya]  관리자페이지, 출퇴근 카드 부트스트랩 적용 commit

eroom/src/main/java/com/eroom/directory/dto/DirectoryDto.java, eroom/src/main/java/com/eroom/directory/dto/DirectoryMemoDto.java, eroom/src/main/java/com/eroom/directory/entity/DirectoryMemo.java, eroom/src/main/java/com/eroom/employee/entity/Separator.java
- Employee, Separator, Directory, DirectoryMemo Entity, Dto 수정,생성
- separator 예약어. 백틱 수정 -> `separator`
=> [ksk] Entity, Dto 수정,생성2_20250414

eroom/src/main/java/com/eroom/calendar/controller/CalendarController.java, eroom/src/main/java/com/eroom/calendar/dto/EmployeeCalendarDto.java, eroom/src/main/java/com/eroom/calendar/repository/EmployeeCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/service/EmployeeCalendarService.java, eroom/src/main/resources/templates/calendar/employeelist.html
=> 개인캘린더 수정 완료

eroom/src/main/java/com/eroom/employee/entity/Employee.java, eroom/src/main/java/com/eroom/mail/contorller/MailController.java, eroom/src/main/java/com/eroom/mail/dto/MailDto.java, eroom/src/main/java/com/eroom/mail/dto/MailReceiverDto.java, eroom/src/main/java/com/eroom/mail/entity/Mail.java, eroom/src/main/java/com/eroom/mail/entity/MailReceiver.java, eroom/src/main/java/com/eroom/mail/repository/MailReceiverRepository.java, eroom/src/main/java/com/eroom/mail/service/MailService.java, eroom/src/main/resources/templates/mail/mailCreate.html
employee > mail, mailReceiver 조인 연결
메일 작성 구현중
=> [Kty] employee > mail, mailReceiver 조인 연결

eroom/src/main/java/com/eroom/project/controller/ProjectController.java, eroom/src/main/java/com/eroom/project/dto/GithubPullRequestDto.java, eroom/src/main/java/com/eroom/project/dto/ProjectDto.java, eroom/src/main/java/com/eroom/project/entity/Project.java, eroom/src/main/java/com/eroom/project/service/ProjectService.java, eroom/src/main/java/com/eroom/rsacryption/RSACryptor.java, eroom/src/main/resources/templates/project/projectDetail.html
- RSA 양방향 암호화로 토큰 암호화 하여 DB에 저장
=> [jhs] Github Pull Request API 적용 완료

eroom/src/main/java/com/eroom/mail/contorller/MailController.java, eroom/src/main/java/com/eroom/mail/dto/MailReceiverDto.java, eroom/src/main/java/com/eroom/mail/service/MailService.java, eroom/src/main/resources/templates/mail/mailCreate.html
메일 작성 > 조직원 정보 불러오기중
구현 상세 ) 선택해서 정보 넣을 수 있도록 구현중
=> Kty 메일 작성부분 구현중

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/dto/ChatroomDto.java, eroom/src/main/java/com/eroom/chat/entity/Chatroom.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/java/com/eroom/employee/repository/EmployeeRepository.java, eroom/src/main/resources/templates/chat/list.html
=> Lyj 채팅방 추가기능 작성중

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java
- 소속에 속한 팀원 조회하는 서비스, 래파지토리 변경
- chatroom => employee
=> [lyj] 소속에 속한 팀원 조회하는 서비스, 래파지토리 변경

eroom/build.gradle, eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/controller/PdfController.java, eroom/src/main/java/com/eroom/approval/controller/PdfController2.java, eroom/src/main/java/com/eroom/employee/entity/Employee.java
[ksk] approval package 오류 수정_20250416
- approval package 오류 수정
=> [ksk] approval package 오류 수정_20250416

eroom/src/main/java/com/eroom/calendar/controller/CalendarController.java, eroom/src/main/java/com/eroom/calendar/dto/CompanyCalendarDto.java, eroom/src/main/java/com/eroom/calendar/entity/CompanyCalendar.java, eroom/src/main/java/com/eroom/calendar/repository/CompanyCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/repository/EmployeeCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/service/CompanyCalendarService.java, eroom/src/main/java/com/eroom/calendar/service/EmployeeCalendarService.java, eroom/src/main/resources/templates/calendar/companylist.html, eroom/src/main/resources/templates/calendar/employeelist.html
개인 캘린더 일부 수정
-등록 시 시간 설정: 시 종료시간이 시작시간보다 과거로 설정하지 못하게
-수정할때도 똑같이 할 수 있도록 해야함
회사 캘린더 진행중
-목록 조회
-상세 조회
-일정 등록
-일정 수정 까지 완료
=> [KYK] 개인캘린더 일부 수정 , 회사 캘린더 진행중

eroom/src/main/java/com/eroom/project/controller/ProjectController.java, eroom/src/main/java/com/eroom/project/dto/ProjectDto.java, eroom/src/main/java/com/eroom/project/dto/ProjectMemberDto.java, eroom/src/main/java/com/eroom/project/entity/Project.java, eroom/src/main/java/com/eroom/project/entity/ProjectMember.java, eroom/src/main/java/com/eroom/project/repository/ProjectMemberRepository.java, eroom/src/main/java/com/eroom/project/service/ProjectService.java, eroom/src/main/java/com/eroom/security/WebSecurityConfig.java, eroom/src/main/resources/templates/project/allProject.html, eroom/src/main/resources/templates/project/projectCreate.html
- 프로젝트 기본 정보 입력
- 프로젝트 PM, 관리자, 참가자 선택
- 시작 날짜로 진행 여부 판단
- github token RSA 암호화 후 데이터베이스 저장
=> [jhs] 프로젝트 생성 완료

eroom/build.gradle, eroom/src/main/java/com/eroom/employee/entity/Employee.java
[ksk] 강사님과 오전 회의 마무리_20250417
- build.graddle 수정 SpringSecurity5 제거 -> 6 사용
- Employee 주석 제거
=> [ksk] 강사님과 오전 회의 마무리_20250417

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/resources/templates/chat/list.html
=> Lyj 그룹채팅방 이름 변경 완료

eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalAlarmDto.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalDto.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalFormatDto.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalLineDto.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalSignatureDto.java, eroom/src/main/java/com/eroom/approval/entity/Approval.java, eroom/src/main/java/com/eroom/approval/entity/ApprovalAlarm.java, eroom/src/main/java/com/eroom/approval/entity/ApprovalFormat.java, eroom/src/main/java/com/eroom/approval/entity/ApprovalLine.java, eroom/src/main/java/com/eroom/approval/entity/ApprovalSignature.java, eroom/src/main/java/com/eroom/approval/repository/ApprovalRepository.java, eroom/src/main/java/com/eroom/approval/service/ApprovalService.java, eroom/src/main/java/com/eroom/directory/entity/Directory.java, eroom/src/main/java/com/eroom/employee/entity/Employee.java, eroom/src/main/resources/templates/approval/myRequestedApprovals.html
[ksk] 결재 조회 기능 진행중1_20250417
- 결재 조회 기능 진행중
- 순환 참조 오류 Employee Entity @ToString.Exclude 추가로 해결
=> [ksk] 결재 조회 기능 진행중1_20250417

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/entity/Chatroom.java, eroom/src/main/java/com/eroom/chat/repository/ChatroomAttendeeRepository.java, eroom/src/main/java/com/eroom/chat/repository/ChatroomRepository.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/resources/templates/chat/list.html
- 1대1 채팅방 생성시 반드시 참여자가 있어야 추가가능
- 생성자 본인을 참여자로 선택 불가
- 이미 존재하는 1대1 채팅방이면 생성불가
=> [lyj] 새 채팅방 만들기 기능추가

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/repository/ChatroomRepository.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/resources/templates/chat/list.html
[lyj] 채팅방 상세 조회 세부기능 추가, 채팅방 목록 조회 기능수정
- 그룹채팅방 참여자 추가하기 완료
- 참여자 목록 조회 완료
- 참여자 기준으로도 채팅목록 조회 완성
=> Lyj 채팅방 상세 조회 세부기능 추가, 채팅방 목록 조회 기능수정

eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/service/ApprovalFormatService.java, eroom/src/main/java/com/eroom/directory/repository/EmployeeDirectoryRepository.java, eroom/src/main/java/com/eroom/directory/service/EmployeeDirectoryService.java, eroom/src/main/resources/templates/approval/create.html
[ksk] 요청한 결재 조회 기능 완료_20250417
- 순환 참조 오류 Employee Entity @ToString.Exclude 추가로 해결
- 요청한 결재 조회 기능 완료(검색 및 정렬 추가 필요)
- StructureService 생성
- 결재 작성 페이지 : 결재 양식 불러오기 기능 완료, 결재자 선택 모달 추가 완료
=> [ksk] 요청한 결재 조회 기능 완료_20250417

eroom/src/main/java/com/eroom/calendar/controller/CalendarController.java, eroom/src/main/java/com/eroom/calendar/dto/CompanyCalendarDto.java, eroom/src/main/java/com/eroom/calendar/dto/TeamCalendarDto.java, eroom/src/main/java/com/eroom/calendar/entity/TeamCalendar.java, eroom/src/main/java/com/eroom/calendar/repository/TeamCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/service/TeamCalendarService.java, eroom/src/main/resources/templates/calendar/companylist.html, eroom/src/main/resources/templates/calendar/employeelist.html, eroom/src/main/resources/templates/calendar/myteamlist.html
-팀캘린더
-팀 일정 등록
-일정 조회
-일정 상세 조회
-일정 수정
-일정 삭제
회사 캘린더
-일정 등록 오류 수정
-관리자만 날짜를 클릭했을 때 등록할 수 있도록 수정
=> [KYK] 팀 캘린더 완료

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/dto/ChatroomDto.java, eroom/src/main/java/com/eroom/chat/repository/ChatMessageRepository.java, eroom/src/main/java/com/eroom/chat/service/ChatMessageService.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/java/com/eroom/chat/specification/ChatMessageSpecification.java, eroom/src/main/java/com/eroom/chat/specification/ChatroomSpecification.java, eroom/src/main/java/com/eroom/websocket/ChatWebSocketHandler.java, eroom/src/main/resources/templates/chat/list.html
- 웹소켓 연결함
- 1대1채팅 그룹채팅 되는거 확인
- 그룹채팅일때 상대방이 누군지 몰라서 이름나오게하는거 해야함
=> [lyj] 채팅방 구현 완료

eroom/src/main/java/com/eroom/attendance/controller/AttendanceController.java, eroom/src/main/java/com/eroom/attendance/dto/AnnualLeaveDto.java, eroom/src/main/java/com/eroom/attendance/entity/AnnualLeave.java, eroom/src/main/java/com/eroom/attendance/repository/AnnualLeaveRepository.java, eroom/src/main/java/com/eroom/attendance/repository/AttendanceRepository.java, eroom/src/main/java/com/eroom/attendance/service/AttendanceService.java, eroom/src/main/java/com/eroom/directory/repository/EmployeeDirectoryRepository.java, eroom/src/main/java/com/eroom/directory/service/EmployeeDirectoryService.java, eroom/src/main/java/com/eroom/employee/entity/Employee.java, eroom/src/main/java/com/eroom/mypage/controller/MyPageController.java, eroom/src/main/resources/templates/attendance/list.html, eroom/src/main/resources/templates/include/nav.html, eroom/src/main/resources/templates/mypage/list.html
- 연차 정보 조회 
- 주소록 정보 조회
- 근태 기록 월별 조회
- 근태 통계 기능 구현 예정
=> [cya] 근태기록 조회 완료

eroom/src/main/java/com/eroom/chat/entity/Chatroom.java, eroom/src/main/java/com/eroom/chat/service/ChatMessageService.java, eroom/src/main/java/com/eroom/websocket/ChatWebSocketHandler.java, eroom/src/main/resources/templates/chat/list.html
=> [lyj] 그룹채팅 완료

eroom/build.gradle, eroom/src/main/java/com/eroom/calendar/controller/CalendarController.java, eroom/src/main/java/com/eroom/calendar/dto/DepartmentCalendarDto.java, eroom/src/main/java/com/eroom/calendar/entity/DepartmentCalendar.java, eroom/src/main/java/com/eroom/calendar/repository/DepartmentCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/repository/TeamCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/service/DepartmentCalendarService.java, eroom/src/main/java/com/eroom/calendar/service/TeamCalendarService.java, eroom/src/main/java/com/eroom/employee/entity/Structure.java, eroom/src/main/java/com/eroom/employee/repository/EmployeeRepository.java, eroom/src/main/java/com/eroom/employee/repository/StructureRepository.java, eroom/src/main/java/com/eroom/employee/service/EmployeeService.java, eroom/src/main/resources/templates/calendar/companylist.html, eroom/src/main/resources/templates/calendar/departlist.html
=> [KYK] 부서 캘린더 완료

eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalRequestDto.java, eroom/src/main/java/com/eroom/approval/entity/Approval.java, eroom/src/main/java/com/eroom/approval/service/ApprovalService.java, eroom/src/main/java/com/eroom/employee/dto/EmployeeDto.java, eroom/src/main/resources/templates/approval/create.html
[ksk] 요청한 결재 작성 기능 1차 완료_20250421
- 결재 작성시 DB insert 완료 확인
- 결재 라인 순서 지정하여 DB 저장 성공
- 양식마다 input 태그들 json 변환을 위한 thymeleaf th:field 추가 수정 필요
- 결재 상세 조회 진행중(선택한 양식에 맞는 템플릿 작성 예정)
=> [ksk] 요청한 결재 작성 기능 1차 완료_20250421

eroom/src/main/java/com/eroom/calendar/controller/CalendarController.java, eroom/src/main/java/com/eroom/calendar/repository/CompanyCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/repository/DepartmentCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/repository/EmployeeCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/repository/TeamCalendarRepository.java, eroom/src/main/java/com/eroom/calendar/service/CompanyCalendarService.java, eroom/src/main/java/com/eroom/calendar/service/DepartmentCalendarService.java, eroom/src/main/java/com/eroom/calendar/service/EmployeeCalendarService.java, eroom/src/main/java/com/eroom/calendar/service/TeamCalendarService.java, eroom/src/main/resources/templates/calendar/departlist.html, eroom/src/main/resources/templates/calendar/list.html
캘린더 전체 일정 조회
-부서
-회사 
일정만 조회할 수 있습니다
=> [KYK] 캘린더 전체일정

eroom/src/main/java/com/eroom/attendance/controller/AttendanceController.java, eroom/src/main/java/com/eroom/attendance/repository/AttendanceRepository.java, eroom/src/main/java/com/eroom/attendance/service/AttendanceService.java, eroom/src/main/resources/templates/attendance/list.html
- 근태 기록 월별 조회 완료
- 근태요약 차트 완료
- 근무시간 통합 차트(일별 근무시간,요일별 평균 근무시간, 이번달 총 근무시간) 완료
=> [cya] 근태 페이지 기능 구현, 차트 반영 완료

eroom/src/main/java/com/eroom/calendar/controller/CalendarController.java, eroom/src/main/java/com/eroom/calendar/service/DepartmentCalendarService.java, eroom/src/main/java/com/eroom/facility/repository/FacilityRepository.java, eroom/src/main/java/com/eroom/facility/service/FacilityService.java, eroom/src/main/java/com/eroom/reservation/controller/ReservationController.java, eroom/src/main/java/com/eroom/reservation/dto/VehicleDto.java, eroom/src/main/java/com/eroom/reservation/entity/Vehicle.java, eroom/src/main/java/com/eroom/reservation/repository/VehicleRepository.java, eroom/src/main/java/com/eroom/reservation/service/VehicleService.java, eroom/src/main/resources/templates/calendar/departlist.html, eroom/src/main/resources/templates/reservation/vehiclerev.html
부서 캘린더
-관리자만 부서캘린더에서 삭제할 수 있게 기능 추가
=> [KYK] 부서 캘린더 일부 수정

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/resources/templates/chat/list.html
- 채팅방 상세모달에서 채팅방이름 안나오는거 수정
- 채팅방 이름변경 안되던거 수정
- 1:1 채팅방 생성시 목록창 상대방 이름으로 나오게 수정
=> Lyj 채팅방 이름변경, 수정, 1대1채팅방수정

eroom/src/main/resources/templates/include/layout.html
- 커서 깜빡임 스타일 태그 일단 주석해놓음
- 38 ~ 42 줄 스타일태그 추가
=> [lyj] 멘토링 할 때 layout.html 수정 

eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/controller/ApprovalLineController.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalFormatDto.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalLineDto.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalRequestDto.java, eroom/src/main/java/com/eroom/approval/entity/ApprovalLine.java, eroom/src/main/java/com/eroom/approval/service/ApprovalLineService.java, eroom/src/main/java/com/eroom/approval/service/ApprovalService.java, eroom/src/main/resources/templates/approval/create.html, eroom/src/main/resources/templates/approval/detail.html
[ksk] 보류 결재, 완료 결재를 사용한 재기안 기능 완료_20250424
- 보류 결재를 사용한 재기안 기능 진행중
- (결재선 불러오기 완료, 제목, 양식 불러오기 완료)
- (양식에 이전 내용 불러오기 진행중)
- (보류 결재를 재기안시 기존 보류 결재 visible Y->N)
- (완료된 결재 재기안시 기존 완료된 결재 visible 수정x)
- 양식 내에 기존 데이터 삽입 완료
- 양식 수정 및 추가 필요
=> [ksk] 보류 결재, 완료 결재를 사용한 재기안 기능 완료_20250424

eroom/src/main/java/com/eroom/survey/controller/SurveyController.java, eroom/src/main/java/com/eroom/survey/dto/SurveyDto.java, eroom/src/main/java/com/eroom/survey/repository/SurveyVoteRepository.java, eroom/src/main/java/com/eroom/survey/repository/SurveyVoterRepository.java, eroom/src/main/java/com/eroom/survey/service/SurveyService.java, eroom/src/main/java/com/eroom/survey/service/SurveyVoteService.java, eroom/src/main/resources/templates/survey/list.html
- 설문 생성
- 생성시 옵션 (다중투표, 익명)
- 생성시 유효성 검사 (제목, 항목, 투표권한자, 마감일)
- 설문 목록 조회 (제목, 작성자, 진행여부, 응답자수, 마감일)
- 설문 상세 조회
- 권한 확인 후 투표
- 득표수, 투표자 표시
- 내 투표 표시
- 재투표
- 마감된 투표 결과
=> [ces] 설문 1차 완료

eroom/src/main/java/com/eroom/drive/contorller/DriveController.java, eroom/src/main/java/com/eroom/drive/dto/DriveDto.java, eroom/src/main/java/com/eroom/drive/entity/Drive.java, eroom/src/main/java/com/eroom/drive/repository/DriveRepository.java, eroom/src/main/java/com/eroom/drive/service/DriveService.java, eroom/src/main/resources/templates/drive/personal.html
- DB drive 에 파일설명 컬럼추가
- 파일업로드 파일설명 추가해서 업로드하게 수정함
- 개인드라이브 목록조회 완성
=> [lyj] 2025-04-24 개인 드라이브 작업중

eroom/src/main/java/com/eroom/reservation/controller/ReservationController.java, eroom/src/main/java/com/eroom/reservation/repository/MeetingRoomRepository.java, eroom/src/main/java/com/eroom/reservation/repository/VehicleRepository.java, eroom/src/main/java/com/eroom/reservation/service/MeetingRoomService.java, eroom/src/main/java/com/eroom/reservation/service/VehicleService.java, eroom/src/main/resources/templates/calendar/list.html, eroom/src/main/resources/templates/reservation/meetingroomrev.html, eroom/src/main/resources/templates/reservation/vehiclerev.html
차량예약,회의실 예약 완료
-차량,회의실 목록조회
-예약 현황 목록조회
-예약 등록
-삭제
=> [KYK]차량예약,회의실 예약 완료

eroom/src/main/java/com/eroom/drive/controller/DriveController.java, eroom/src/main/java/com/eroom/drive/repository/DriveRepository.java, eroom/src/main/java/com/eroom/drive/service/DriveService.java, eroom/src/main/resources/templates/drive/personal.html
=> [lyj] 2025-04-25 개인 드라이브 작업중

eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/controller/ApprovalPdfController.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalAlarmDto.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalDto.java, eroom/src/main/java/com/eroom/approval/entity/Approval.java, eroom/src/main/java/com/eroom/approval/entity/ApprovalAlarm.java, eroom/src/main/java/com/eroom/approval/repository/ApprovalAlarmRepository.java, eroom/src/main/java/com/eroom/approval/service/ApprovalAlarmService.java, eroom/src/main/java/com/eroom/approval/service/ApprovalService.java, eroom/src/main/java/com/eroom/employee/entity/Employee.java, eroom/src/main/java/com/eroom/websocket/ApprovalWebSocketHandler.java, eroom/src/main/java/com/eroom/websocket/CustomHandshakeInterceptor.java, eroom/src/main/java/com/eroom/websocket/WebSocketConfig.java, eroom/src/main/resources/templates/approval/detail.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/templatePdf/detailPdfTemplate.html, eroom/src/main/resources/templates/include/layout.html
[ksk] 웹소켓 연결 완료(layout)_20250427
- 웹소켓 알림 연결 확인 완료.
- (layout에 웹소켓 연결 만들어놨습니다.)
- 결재 최종승인 또는 반려시 알림 메세지 DB 저장 확인 완료.
=> [ksk] 웹소켓 연결 완료(layout)_20250427

eroom/src/main/resources/templates/include/layout.html
[ksk] 웹소켓 연결 완료(layout) 오류 코드 제거_20250428
- 웹소켓 연결 완료(layout) 오류 코드 제거
=> [ksk] 웹소켓 연결 완료(layout) 오류 코드 제거_20250428

eroom/src/main/java/com/eroom/drive/controller/DriveController.java, eroom/src/main/java/com/eroom/drive/dto/DriveDto.java, eroom/src/main/java/com/eroom/drive/entity/Drive.java, eroom/src/main/java/com/eroom/drive/repository/DriveRepository.java, eroom/src/main/java/com/eroom/drive/service/DriveService.java, eroom/src/main/java/com/eroom/mail/service/MailService.java, eroom/src/main/java/com/eroom/websocket/CustomHandshakeInterceptor.java, eroom/src/main/resources/templates/chat/list.html, eroom/src/main/resources/templates/include/layout.html
- 드라이브 delete_yn DB컬럼,엔티티,DTO 삭제
- 드라이브 visible_yn 으로 변경
- 드라이브 다운로드시 mod_date 안바뀌게수정
- 파일경로 drive/personal 로바꿈
=> [lyj] 드라이브 수정

eroom/src/main/java/com/eroom/reservation/controller/ReservationController.java, eroom/src/main/resources/templates/reservation/vehiclerev.html
secret properties에 tmap key 추가 했습니다
=> [KYK] secret properties에 tmap key 추가

eroom/src/main/java/com/eroom/employee/controller/EmployeeController.java, eroom/src/main/java/com/eroom/security/MyLoginSuccessHandler.java, eroom/src/main/resources/templates/include/layout.html, eroom/src/main/resources/templates/login.html
[ksk] 웹소켓 연결 완료(layout) 오류 코드 수정 완료_20250428
- 웹소켓 연결 완료(layout) 오류 코드 제거
- 오류 코드 수정 완료
- (임시 : approval 관련 페이지만 웹소켓 동작 확인 완료.)
- (임시 : 다른 페이지 접속 가능하게 수정 완료.)
=> [ksk] 웹소켓 연결 완료(layout) 오류 코드 수정 완료_20250428

eroom/src/main/java/com/eroom/reservation/controller/ReservationController.java, eroom/src/main/java/com/eroom/reservation/dto/MeetingRoomDto.java, eroom/src/main/java/com/eroom/reservation/service/MeetingRoomService.java, eroom/src/main/resources/templates/calendar/companylist.html, eroom/src/main/resources/templates/calendar/departlist.html, eroom/src/main/resources/templates/calendar/employeelist.html, eroom/src/main/resources/templates/calendar/list.html, eroom/src/main/resources/templates/calendar/myteamlist.html, eroom/src/main/resources/templates/include/layout.html, eroom/src/main/resources/templates/include/nav.html, eroom/src/main/resources/templates/reservation/meetingroomrev.html, eroom/src/main/resources/templates/reservation/vehiclerev.html
=> [Kyk] nav바 수정

eroom/src/main/java/com/eroom/drive/controller/DriveController.java, eroom/src/main/resources/templates/drive/team.html
- 팀 드라이브 일괄다운로드 작성(중복된이름 파일이 있으면 파일이름 뒤에 (1)씩 카운트 늘어남)
- 개인드라이브 일괄다운로드 수정(중복된이름 파일이 있으면 파일이름 뒤에 (1)씩 카운트 늘어남)
- 팀 드라이브 일괄삭제 완성
=> [lyj] 팀 드라이브 작성완료

eroom/src/main/java/com/eroom/drive/controller/DriveController.java, eroom/src/main/resources/templates/drive/personal.html
- 개인 드라이브 입장시 사용자이름으로 ooo님 드라이브 이런식으로 나옴
- 검색,정렬,페이징 고침
=> [lyj] 개인드라이브 수정 함

eroom/src/main/java/com/eroom/approval/controller/ApprovalSignatureController.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalSignatureDto.java, eroom/src/main/java/com/eroom/approval/entity/ApprovalSignature.java, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/include/layout.html
[ksk] 시그니처패드 불러오기 테스트 성공_20250428
- 시그니처패드 Entity, Dto 수정 완료
- 시그니처패드 불러오기 테스트 성공
- layout에 SignaturePad 라이브러리 코드 추가
- 시그니처패드를 사용한 사원별 서명 정보 CRUD 진행 예정
=> [ksk] 시그니처패드 불러오기 테스트 성공_20250428

eroom/src/main/java/com/eroom/drive/controller/DriveController.java, eroom/src/main/java/com/eroom/drive/dto/DriveDto.java, eroom/src/main/java/com/eroom/drive/repository/DriveRepository.java, eroom/src/main/java/com/eroom/drive/service/DriveService.java, eroom/src/main/java/com/eroom/employee/repository/SeparatorRepository.java, eroom/src/main/java/com/eroom/employee/service/StructureService.java, eroom/src/main/resources/templates/drive/department.html, eroom/src/main/resources/templates/drive/personal.html
- 부서드라이브 조회 완료
- 부서드라이브 파일업로드 완료
- 부서드라이브 본인이 올린글만 수정완료
- 부서드라이브 본인이 올린글만 삭제완료
- 부서드라이브 파일 다운로드 완료
- 부서드라이브 파일 일괄 다운로드 완료
=> [lyj] 부서드라이브 완료

eroom/src/main/java/com/eroom/drive/controller/DriveController.java, eroom/src/main/java/com/eroom/drive/repository/DriveRepository.java, eroom/src/main/java/com/eroom/drive/service/DriveService.java, eroom/src/main/resources/templates/drive/company.html, eroom/src/main/resources/templates/drive/department.html, eroom/src/main/resources/templates/drive/personal.html, eroom/src/main/resources/templates/drive/team.html
- 회사드라이브 조회 완료
- 회사드라이브 파일업로드 완료(관리자)
- 회사드라이브 수정완료(관리자)
- 회사드라이브 삭제완료(관리자)
- 회사드라이브 파일 다운로드 완료
- 회사드라이브 파일 일괄 다운로드 완료
- 회사드라이브 파일 일괄 삭제 완료(관리자)
=> [lyj] 회사 드라이브 완료

eroom/src/main/java/com/eroom/drive/controller/DriveController.java, eroom/src/main/java/com/eroom/drive/dto/PersonalDriveSummaryDto.java, eroom/src/main/java/com/eroom/drive/repository/DriveRepository.java, eroom/src/main/java/com/eroom/drive/service/DriveService.java, eroom/src/main/resources/templates/drive/personal.html
- 파일 토탈 사용량 조회 완성
- 전체 파일수 조회 완성
- 총 다운로드 수 조회 완성
- 최근 업로드 일자 조회 완성
=> [lyj] 개인드라이브 파일 세부정보 카드 수정완료

eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalDto.java, eroom/src/main/resources/templates/approval/agreementApprovals.html, eroom/src/main/resources/templates/approval/cardFragment.html, eroom/src/main/resources/templates/approval/fallBackApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovalsBackup.html, eroom/src/main/resources/templates/approval/receivedApprovals.html
[ksk] 결재 검색, 필터 기능 추가 완료_20250429
- 시그니처패드 사원별 저장, 불러오기, 수정, 삭제(visible -> N) 완료
- 결재 검색, 필터 기능 추가 완료
=> [ksk] 결재 검색, 필터 기능 추가 완료_20250429

eroom/src/main/java/com/eroom/project/controller/ProjectController.java, eroom/src/main/java/com/eroom/project/controller/ProjectTodoController.java, eroom/src/main/java/com/eroom/project/dto/EditTodoDetailRequest.java, eroom/src/main/java/com/eroom/project/dto/ProjectTodoElementDetailDto.java, eroom/src/main/java/com/eroom/project/dto/ProjectTodoElementDto.java, eroom/src/main/java/com/eroom/project/dto/TodoDetailResponseDto.java, eroom/src/main/java/com/eroom/project/entity/ProjectTodoElement.java, eroom/src/main/java/com/eroom/project/entity/ProjectTodoElementDetail.java, eroom/src/main/java/com/eroom/project/repository/ProjectTodoElementDetailRepository.java, eroom/src/main/java/com/eroom/project/service/ProjectTodoService.java, eroom/src/main/resources/templates/project/projectDetailTodoTab.html
- 각 할 일 카드 디테일 모달창
- 모달창 내 세부 할 일 표시
- 세부 할 일 체크 여부 데이터베이스 반영 및 할 일 카드에 완료개수/총개수 표시
- 세부 할 일 수정 삭제 추가 기능 및 할 일 카드에 완료개수/총개수 표시
=> [jhs] 프로젝트 할 일 탭 칸반보드 세부 할 일 작업 완료

eroom/src/main/java/com/eroom/drive/controller/DriveController.java, eroom/src/main/java/com/eroom/drive/dto/DriveDto.java, eroom/src/main/java/com/eroom/drive/repository/DriveRepository.java, eroom/src/main/resources/templates/drive/company.html, eroom/src/main/resources/templates/drive/department.html, eroom/src/main/resources/templates/drive/personal.html, eroom/src/main/resources/templates/drive/team.html
=> [lyj] 드라이브 완성

eroom/src/main/java/com/eroom/directory/controller/DirectoryController.java, eroom/src/main/java/com/eroom/directory/controller/DirectoryMemoController.java, eroom/src/main/java/com/eroom/directory/dto/DirectoryMemoDto.java, eroom/src/main/java/com/eroom/directory/entity/DirectoryMemo.java, eroom/src/main/java/com/eroom/directory/repository/DirectoryMemoRepository.java, eroom/src/main/java/com/eroom/directory/service/DirectoryMemoService.java, eroom/src/main/resources/templates/directory/employeeList.html
[ksk] 주소록 프로필 카드 기능 조회 완료, 메모 기능 완료_202504230
- 주소록 프로필 카드 기능 : 기본 정보 조회 완료
- 주소록 메모 기능 : 생성, 조회, 수정, 삭제 기능 완료
=> [ksk] 주소록 프로필 카드 기능 조회 완료, 메모 기능 완료_202504230

eroom/src/main/java/com/eroom/calendar/service/TeamCalendarService.java, eroom/src/main/java/com/eroom/employee/repository/EmployeeRepository.java, eroom/src/main/java/com/eroom/notification/CalendarAlarmService.java, eroom/src/main/java/com/eroom/notification/controller/NotificationController.java, eroom/src/main/java/com/eroom/notification/repository/CalendarAlarmRepository.java, eroom/src/main/java/com/eroom/websocket/TeamAlarmSocketHandler.java, eroom/src/main/java/com/eroom/websocket/WebSocketConfig.java, eroom/src/main/resources/templates/calendar/companylist.html, eroom/src/main/resources/templates/calendar/employeelist.html, eroom/src/main/resources/templates/calendar/myteamlist.html, eroom/src/main/resources/templates/include/header.html, eroom/src/main/resources/templates/include/layout.html, eroom/src/main/resources/templates/reservation/meetingroomrev.html, eroom/src/main/resources/templates/reservation/vehiclerev.html
[kyk] 캘린더 수정 , 알림 팀,회사 완료
-본인 소속 팀 일정 등록하면 알림
-회사 일정 등록하면 모든 인원에게 알림
-캘린더 dateClick 이벤트 제거
=> [kyk] 캘린더 일부 수정, 예약하기 일부 수정, 알림 완료

eroom/src/main/java/com/eroom/mypage/controller/MyPageController.java, eroom/src/main/resources/templates/mypage/list.html, eroom/src/main/resources/templates/mypage/listExample.html
- 근태 페이지 + 마이페이지 합칠 예정
- css 깨짐 문제 해결중
-  각 정보 불러 올 수 있는 것만 불러옴
=> [cya] 마이페이지 작업중

eroom/src/main/java/com/eroom/directory/controller/DirectoryController.java, eroom/src/main/java/com/eroom/directory/service/DirectoryMemoService.java, eroom/src/main/resources/templates/approval/agreementApprovals.html, eroom/src/main/resources/templates/approval/cardFragment.html, eroom/src/main/resources/templates/approval/fallBackApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/receivedApprovals.html, eroom/src/main/resources/templates/approval/referencedApprovals.html
[ksk] 결재 필터+검색+페이징 적용 완료_20250502
- 결재 : 검색, 비동기 필터 기능 + 페이징 적용 완료
=> [ksk] 결재 필터+검색+페이징 적용 완료_20250502

eroom/src/main/java/com/eroom/mail/entity/Mail.java, eroom/src/main/resources/templates/mail/mailTrash.html
=> [kty] mail entity수정

eroom/src/main/java/com/eroom/admin/controller/AdminController.java, eroom/src/main/java/com/eroom/admin/dto/CreateEmployeeDto.java, eroom/src/main/java/com/eroom/directory/entity/Directory.java, eroom/src/main/java/com/eroom/employee/dto/EmployeeUpdateDto.java, eroom/src/main/java/com/eroom/employee/service/EmployeeService.java, eroom/src/main/java/com/eroom/mypage/controller/MyPageController.java, eroom/src/main/resources/templates/admin/employeeManagement.html, eroom/src/main/resources/templates/attendance/list.html, eroom/src/main/resources/templates/mypage/list.html, eroom/src/main/resources/templates/mypage/mypageBackup.html
- 마이페이지 + 근태 페이지 병합 작업 완료
- 회원 생성, 수정 시 주소 API 반영 완료
- 회원 수정시에도 이름 중복 확인 기능 추가
- Directory 엔티티 수정 -> directory_address,directory_zipcode 컬럼 추가
=> [cya] 마이페이지 + 근태페이지 / 회원 생성&수정 변경

eroom/src/main/java/com/eroom/admin/controller/AdminController.java, eroom/src/main/java/com/eroom/directory/controller/DirectoryController.java, eroom/src/main/java/com/eroom/employee/repository/StructureRepository.java, eroom/src/main/java/com/eroom/employee/service/StructureService.java, eroom/src/main/resources/templates/approval/agreementApprovals.html, eroom/src/main/resources/templates/approval/fallBackApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/receivedApprovals.html, eroom/src/main/resources/templates/approval/referencedApprovals.html, eroom/src/main/resources/templates/directory/employeeList.html
[ksk] 주소록 트리구조, 필터, 검색 기능 완료_20250502
- 주소록 : 트리구조, 검색, 비동기 필터 기능 + 페이징 적용 완료
- 오류수정 : AdminController impot LocalDateTime 추가
- 주소록 : 트리구조, 필터 동기화 완료
- 공용 트리구조 작업 진행 예정
=> [ksk] 주소록 트리구조, 필터, 검색 기능 완료_20250502

eroom/src/main/java/com/eroom/attendance/service/AttendanceService.java, eroom/src/main/java/com/eroom/drive/controller/ProfileController.java, eroom/src/main/java/com/eroom/drive/service/ProfileService.java, eroom/src/main/java/com/eroom/employee/service/EmployeeService.java, eroom/src/main/java/com/eroom/home/controller/HomeController.java, eroom/src/main/java/com/eroom/mypage/controller/MyPageController.java, eroom/src/main/resources/templates/admin/employeeManagement.html, eroom/src/main/resources/templates/index.html, eroom/src/main/resources/templates/mypage/list.html
- 개인정보(주소록) 수정 구현
- 홈화면 출퇴근 버튼 시간 오류 해결
- 프로필 사진 반영 예정
=> [cya] 마이페이지 개인정보 수정 완료

eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/repository/ApprovalRepository.java, eroom/src/main/java/com/eroom/approval/service/ApprovalService.java, eroom/src/main/java/com/eroom/directory/controller/DirectoryController.java, eroom/src/main/java/com/eroom/directory/dto/AddDepartmentAndTeamDto.java, eroom/src/main/java/com/eroom/directory/dto/DepartmentSortDto.java, eroom/src/main/java/com/eroom/directory/dto/TeamSortDto.java, eroom/src/main/java/com/eroom/directory/dto/UpdateSortOrderDto.java, eroom/src/main/java/com/eroom/employee/dto/StructureDto.java, eroom/src/main/java/com/eroom/employee/entity/Separator.java, eroom/src/main/java/com/eroom/employee/entity/Structure.java, eroom/src/main/java/com/eroom/employee/repository/StructureRepository.java, eroom/src/main/java/com/eroom/employee/service/StructureService.java, eroom/src/main/resources/templates/approval/agreementApprovals.html, eroom/src/main/resources/templates/approval/cardFragment.html, eroom/src/main/resources/templates/approval/create.html, eroom/src/main/resources/templates/approval/fallBackApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/receivedApprovals.html, eroom/src/main/resources/templates/approval/referencedApprovals.html, eroom/src/main/resources/templates/directory/employeeList.html, eroom/src/main/resources/templates/directory/employeeListFragment.html
[ksk] 부서, 팀 추가 기능 완료_20250505
- structure Entity pk 속성 추가(@GeneratedValue(strategy = GenerationType.IDENTITY))
- separator Entity reg_date, mode_date 속성 추가(insertable = false, updatable = false)
- 부서 추가 기능 완료.
- 팀 추가 기능 완료.
=> [ksk] 부서, 팀 추가 기능 완료_20250505

eroom/src/main/java/com/eroom/admin/controller/AdminController.java, eroom/src/main/java/com/eroom/reservation/repository/MeetingRoomRepository.java, eroom/src/main/java/com/eroom/reservation/repository/VehicleRepository.java, eroom/src/main/java/com/eroom/reservation/service/MeetingRoomService.java, eroom/src/main/java/com/eroom/reservation/service/VehicleService.java, eroom/src/main/resources/templates/admin/meetingroom.html, eroom/src/main/resources/templates/admin/vehicle.html, eroom/src/main/resources/templates/mypage/list.html
- 차량 목록, 차량 예약 목록 조회
- 회의실 목록, 회의실 예약 목록 조회
=> [cya] 차량/회의실 관리 페이지 목록 조회 완료

eroom/src/main/java/com/eroom/project/controller/ProjectMinuteController.java, eroom/src/main/java/com/eroom/project/dto/ProjectMeetingMinuteDto.java, eroom/src/main/java/com/eroom/project/entity/ProjectMeetingMinute.java, eroom/src/main/java/com/eroom/project/repository/ProjectMeetingMinuteRepository.java, eroom/src/main/java/com/eroom/project/service/ProjectMeetingMinuteService.java, eroom/src/main/resources/templates/project/projectMinuteCreate.html, eroom/src/main/resources/templates/project/projectMinuteDetail.html
=> [ces] 회의록 완료

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/resources/templates/chat/list.html
=> [lyj] 채팅파일 수정

eroom/src/main/java/com/eroom/approval/entity/Approval.java, eroom/src/main/java/com/eroom/approval/service/ApprovalService.java
[ksk] 결재 등록 오류 수정_20250506
- 결재 오류 수정(visible Y insert오류)
=> [ksk] 결재 등록 오류 수정_20250506

eroom/src/main/java/com/eroom/employee/controller/EmployeeController.java, eroom/src/main/java/com/eroom/security/EmployeeDetails.java, eroom/src/main/java/com/eroom/security/MyLoginFailureHandler.java, eroom/src/main/java/com/eroom/security/WebSecurityConfig.java, eroom/src/main/resources/templates/include/header.html, eroom/src/main/resources/templates/login.html
- 모달창 변경
- 아이디 및 비밀번호 미일치 시 알람
- 퇴사자 로그인 불가 알람
- 자동로그인 기능 추가
- 로그아웃 기능 추가
=> [jhs] 로그인 기능 수정 및 추가

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/websocket/ChatWebSocketHandler.java, eroom/src/main/resources/templates/chat/list.html
=> [lyj] 채팅파일 완료

eroom/src/main/resources/templates/mypage/list.html
=> [jhs] 마이페이지 프로젝트 표시 수정

eroom/src/main/java/com/eroom/article/controller/ArticleController.java, eroom/src/main/java/com/eroom/article/repository/ArticleRepository.java, eroom/src/main/java/com/eroom/article/service/ArticleService.java, eroom/src/main/java/com/eroom/mail/contorller/MailController.java, eroom/src/main/java/com/eroom/mail/dto/MailAlarmDto.java, eroom/src/main/java/com/eroom/mail/repository/MailStatusRepository.java, eroom/src/main/java/com/eroom/mail/service/MailService.java, eroom/src/main/java/com/eroom/websocket/MailWebSocketHandler.java, eroom/src/main/resources/templates/article/articleDetail.html, eroom/src/main/resources/templates/article/articleEdit.html, eroom/src/main/resources/templates/mail/mailImportant.html, eroom/src/main/resources/templates/mail/mailReceiverTo.html, eroom/src/main/resources/templates/mail/mailReceiverToFragment.html
-메일 
웹소켓 오류 수정  = > location.reload();로 일단 처리
메일 알람 toDto 메소드 생성
-게시판
게시판 수정 작업중(파일 삭제)
=> Kty 05/07 메일 웹소켓 오류 수정, 게시판 수정 작업중(파일 삭제)

eroom/src/main/java/com/eroom/chat/dto/ChatAlarmDto.java, eroom/src/main/java/com/eroom/notification/CalendarAlarmService.java, eroom/src/main/java/com/eroom/notification/controller/NotificationController.java, eroom/src/main/java/com/eroom/notification/dto/AlarmDto.java, eroom/src/main/java/com/eroom/notification/entity/Alarm.java, eroom/src/main/java/com/eroom/notification/repository/AlarmRepository.java, eroom/src/main/java/com/eroom/notification/repository/CalendarAlarmRepository.java, eroom/src/main/java/com/eroom/notification/service/AlarmService.java, eroom/src/main/resources/templates/include/header.html, eroom/src/main/resources/templates/notification/notification.html
-헤더 종 목록 조회
-헤더 종 목록에서 하나 누르면 N->Y 처리
-종 목록은 N 인 상태만 조회 가능
-알림 페이지 목록조회
=> [kyk] 알림 완료

eroom/src/main/java/com/eroom/calendar/controller/CalendarController.java, eroom/src/main/java/com/eroom/calendar/dto/CalendarAlarmDto.java, eroom/src/main/java/com/eroom/calendar/entity/CalendarAlarm.java, eroom/src/main/java/com/eroom/calendar/repository/CalendarAlarmRepository.java, eroom/src/main/java/com/eroom/calendar/service/CalendarAlarmService.java, eroom/src/main/java/com/eroom/calendar/service/CompanyCalendarService.java, eroom/src/main/java/com/eroom/calendar/service/TeamCalendarService.java, eroom/src/main/java/com/eroom/notification/controller/NotificationController.java, eroom/src/main/java/com/eroom/notification/dto/AlarmDto.java, eroom/src/main/java/com/eroom/notification/entity/Alarm.java, eroom/src/main/java/com/eroom/notification/repository/AlarmRepository.java, eroom/src/main/java/com/eroom/notification/service/AlarmService.java, eroom/src/main/resources/templates/notification/notification.html, eroom/src/main/resources/templates/reservation/meetingroomrev.html, eroom/src/main/resources/templates/reservation/vehiclerev.html
-오늘 어제 전 날짜는 날짜로 표기
-예약 페이지 날짜 - 에서 . 으로 변경
=> [KYK] 알람 페이지 수정, 예약 페이지 수정

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/drive/repository/DriveRepository.java, eroom/src/main/java/com/eroom/nav/controller/GlobalModelAttributeConfig.java, eroom/src/main/java/com/eroom/nav/service/NavService.java, eroom/src/main/java/com/eroom/websocket/ChatWebSocketHandler.java, eroom/src/main/java/com/eroom/websocket/WebMvcConfig.java, eroom/src/main/resources/templates/chat/list.html
- 1대1 채팅방목록,메시지,상세정보 프로필완성
- 채팅방 들어갈시 스크롤바 제일 하단으로 포커싱
=> [lyj] 채팅방 기능 추가중

eroom/src/main/resources/templates/reservation/vehiclerev.html
전체 캘린더 url 변경
calendar -> calendar/all 로 변경
=> [kyk] 전체 캘린더 url 변경

eroom/src/main/java/com/eroom/project/controller/ProjectController.java, eroom/src/main/java/com/eroom/project/service/ProjectService.java, eroom/src/main/resources/templates/project/projectDetailFilesTab.html, eroom/src/main/resources/templates/project/projectDetailMain.html
=> [jhs] 프로젝트 권한에 따른 접근 제한 설정 중

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/repository/ChatroomRepository.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/resources/templates/chat/list.html, eroom/src/main/resources/templates/directory/employeeList.html
- employeeList.html 수정
- 1대1채팅하기 기능추가
- 채팅방있을시 찾아서 바로가기
- 없을시 새로생성후 바로가기
=> [lyj] 채팅방 기능 추가 

eroom/src/main/java/com/eroom/websocket/ApprovalWebSocketHandler.java, eroom/src/main/resources/templates/approval/detail.html
[ksk] 결재 상세 페이지 css 수정 완료, 웹소켓,알람 진행중3_20250508
- 결재 상세 페이지 css 수정 완료
- 홈화면 알람 웹소켓 연결 완료
- 캘린더 + 결재 알림 1차 완료
- 헤더 종 아이콘 수정 완료
=> [ksk] 결재 상세 페이지 css 수정 완료, 웹소켓,알람 진행중3_20250508

eroom/src/main/java/com/eroom/approval/service/ApprovalAlarmService.java, eroom/src/main/java/com/eroom/employee/controller/EmployeeController.java, eroom/src/main/java/com/eroom/home/controller/HomeController.java, eroom/src/main/java/com/eroom/notification/controller/NotificationController.java, eroom/src/main/java/com/eroom/notification/dto/AlarmDto.java, eroom/src/main/java/com/eroom/notification/service/AlarmService.java, eroom/src/main/java/com/eroom/websocket/ApprovalWebSocketHandler.java, eroom/src/main/resources/templates/include/header.html, eroom/src/main/resources/templates/include/layout.html, eroom/src/main/resources/templates/notification/notification.html
[ksk] 결재 상세 페이지 css 수정 완료, 웹소켓,알람 완료_20250508
- 결재 상세 페이지 css 수정 완료
- 홈화면 알람 웹소켓 연결 완료
- 캘린더 + 결재 알림 1차 완료
- 헤더 종 아이콘 수정 완료
- 헤더 종 - 알람 관련 결재 상세 페이지 이동 기능 완료.
- 주소록 프로필 이미지 조회 진행 예정
=> [ksk] 결재 상세 페이지 css 수정 완료, 웹소켓,알람 완료_20250508

eroom/src/main/resources/templates/hometest/calendartest.html, eroom/src/main/resources/templates/index.html
=> [kyk] 홈화면 전체 캘린더 추가

eroom/src/main/resources/templates/hometest/calendartest.html, eroom/src/main/resources/templates/index.html
=> [kyk] 홈 화면 켈린더 수정

eroom/src/main/java/com/eroom/calendar/service/CalendarAlarmService.java, eroom/src/main/java/com/eroom/notification/controller/NotificationController.java, eroom/src/main/java/com/eroom/notification/service/AlarmService.java, eroom/src/main/resources/templates/include/header.html, eroom/src/main/resources/templates/index.html
=> [kyk] header.html confilct 해결

eroom/src/main/java/com/eroom/article/service/ArticleService.java, eroom/src/main/resources/templates/article/articleNotice.html, eroom/src/main/resources/templates/include/layout.html
=> Kty layout 메일 (빨간점 표시알람) 적용 

eroom/src/main/java/com/eroom/calendar/controller/CalendarController.java, eroom/src/main/java/com/eroom/home/controller/HomeController.java, eroom/src/main/java/com/eroom/reservation/controller/ReservationController.java, eroom/src/main/resources/templates/include/layout.html, eroom/src/main/resources/templates/index.html
=> [kyk] 홈화면 예약현황 크기 수정

eroom/src/main/java/com/eroom/mail/service/MailService.java, eroom/src/main/java/com/eroom/notification/service/AlarmService.java, eroom/src/main/resources/templates/include/header.html
종(알람) 클릭시 해당 mail로 가기 
alram serivce에 접근 메소드 추가
=> Kty 종(알람) 클릭시 해당 mail로 가기 

eroom/build.gradle, eroom/src/main/java/com/eroom/weather/controller/WeatherController.java, eroom/src/main/java/com/eroom/weather/controller/WeatherPageController.java, eroom/src/main/java/com/eroom/weather/dto/WeatherDto.java, eroom/src/main/java/com/eroom/weather/service/WeatherService.java, eroom/src/main/resources/templates/weather/weather.html
- weather.html에다가 적용함
- application-secret.properties api.key 추가
- build.gradle 의존성추가
- GPS 기반 자기위치 날씨 가져오기 성공
- select 로 다른위치 날씨보기 가능
=> [lyj] 날씨 API 추가완료

eroom/src/main/resources/templates/index.html, eroom/src/main/resources/templates/weather/weather.html
=> [lyj] 날씨API 적용

eroom/src/main/resources/templates/index.html
=> [lyj] 뉴스 APi 수정

eroom/src/main/resources/templates/index.html
=> [lyj] index.html 날씨 수정

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/repository/ChatroomAttendeeRepository.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/resources/templates/chat/list.html
[lyj] 채팅방 기능추가및수정
- 채팅방 나가기 기능추가(채팅방에 1명이하일때 채팅방삭제)
- 채팅방 삭제 기능 생성자만 보이게함
=> [lyj] 채팅방 기능추가및수정

eroom/src/main/java/com/eroom/approval/controller/ApprovalController.java, eroom/src/main/java/com/eroom/approval/dto/ApprovalRequestDto.java, eroom/src/main/java/com/eroom/approval/service/ApprovalService.java, eroom/src/main/java/com/eroom/websocket/ApprovalWebSocketHandler.java, eroom/src/main/resources/templates/approval/create.html, eroom/src/main/resources/templates/approval/detail.html
[ksk] 결재 백엔드 로직 수정 완료_20250510
- 기존:사원만 선택 -> 수정:부서,팀 적용 가능
- 결재 상세 페이지 pdf 버튼 수정
=> [ksk] 결재 백엔드 로직 수정 완료_20250510

eroom/src/main/java/com/eroom/directory/controller/DirectoryBookmarkController.java, eroom/src/main/java/com/eroom/directory/controller/DirectoryController.java, eroom/src/main/java/com/eroom/directory/dto/DirectoryBookmarkDto.java, eroom/src/main/java/com/eroom/directory/dto/DirectoryDto.java, eroom/src/main/java/com/eroom/directory/entity/Directory.java, eroom/src/main/java/com/eroom/directory/entity/DirectoryBookmark.java, eroom/src/main/java/com/eroom/directory/repository/DirectoryBookmarkRepository.java, eroom/src/main/java/com/eroom/directory/service/DirectoryBookmarkService.java, eroom/src/main/resources/templates/directory/employeeList.html, eroom/src/main/resources/templates/directory/employeeListFragment.html, eroom/src/main/resources/templates/index.html
[ksk] 홈화면 결재 카드 css 수정, 북마크 추가,고정 기능 완료_20250511
- 홈화면 결재 카드 css 수정
- 북마크 기능 추가 완료
- 북마크 리스트 상위 고정 기능 완료
=> [ksk] 홈화면 결재 카드 css 수정, 북마크 추가,고정 기능 완료_20250511

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/chat/service/ChatroomService.java, eroom/src/main/resources/templates/chat/list.html, eroom/src/main/resources/templates/index.html
- 뉴스 API 무료플랜 리로드 오류 수정
- 5초마다 기존 뉴스 슬라이드됨 20분마다 새로운뉴스로 수정
=> [lyj] 뉴스 API 수정 

eroom/src/main/resources/templates/index.html
- 잘못된 문법 삭제. Line933. if(false){ << 삭제 처리 완료.
=> [ksk] index.html JS 수정_20250511

eroom/src/main/resources/templates/approval/agreementApprovals.html, eroom/src/main/resources/templates/approval/detail.html, eroom/src/main/resources/templates/approval/fallBackApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/receivedApprovals.html, eroom/src/main/resources/templates/approval/referencedApprovals.html, eroom/src/main/resources/templates/directory/employeeList.html, eroom/src/main/resources/templates/directory/employeeListFragment.html, eroom/src/main/resources/templates/index.html
[ksk] index.html JS 수정, 홈화면 추가 수정, 한글화 수정_20250511
- 잘못된 문법 삭제. Line933. if(false){ << 삭제 처리 완료.
- 주소록 email a태그 메일 보내기 페이지 이동 기능 추가.
- admin 부서/팀 정렬, 추가, 삭제 버튼 css 수정.
- 홈화면 결재 카드 미출력시 문구 수정.
- 결재 필터 문구 한글화 및 오류 수정.
=> [ksk] index.html JS 수정, 홈화면 추가 수정, 한글화 수정_20250511

eroom/src/main/resources/templates/approval/agreementApprovals.html, eroom/src/main/resources/templates/approval/fallBackApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/receivedApprovals.html, eroom/src/main/resources/templates/approval/referencedApprovals.html, eroom/src/main/resources/templates/directory/employeeList.html, eroom/src/main/resources/templates/directory/partnerList.html
[ksk] 주소록, 결재 페이지 로딩 스피너 적용 완료_20250511
- 직원 주소록 로딩 스피너 적용 완료
- 협력업체 주소록 로딩 스피너 적용 완료
- 결재 로딩 스피너 적용 완료
- 결재 필터 css 추가 수정
=> [ksk] 주소록, 결재 페이지 로딩 스피너 적용 완료_20250511

eroom/src/main/java/com/eroom/mail/contorller/MailController.java, eroom/src/main/java/com/eroom/mail/repository/MailRepository.java, eroom/src/main/resources/templates/mail/mailCreate.html, eroom/src/main/resources/templates/mail/mailCreateDraft.html, eroom/src/main/resources/templates/mail/mailCreateReply.html, eroom/src/main/resources/templates/mail/mailDraftUpdate.html
트리구조 
메일 작성 페이지 (o)
메일 임시저장 - (o)
답장, 주소록에서 메일쓰기 - (△)
==
메일 작성 유효성 추가
받는 사람 한명이상
=> Kty 트리 적용 작업중 + 메일 받는 사람 유효성 검사

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/java/com/eroom/news/controller/NewsController.java, eroom/src/main/java/com/eroom/news/service/NewsApiService.java, eroom/src/main/resources/templates/index.html
=> [lyj] 뉴스 API 캐시 수정중

eroom/src/main/java/com/eroom/directory/controller/DirectoryController.java, eroom/src/main/resources/templates/directory/employeeListFragment.html
- 결재 합의자 결재 오류 해결
- 한글화 작업 완료
- indexBackup.html - 이전 버전 index입니다. 작업시 참고해주세요.
- 반응형 홈화면 결재 카드 css 작업 완료
- 결재 승인,대기,반려 svg이미지 추가
- 사원 북마크시 해당하는 사원의 번호가 빠지는 경우가 생기는 오류 해결
=> [ksk] 회사 주소록 번호 오류 해결 완료_20250512

eroom/src/main/resources/templates/index.html, eroom/src/main/resources/templates/reservation/meetingroomrev.html, eroom/src/main/resources/templates/reservation/vehiclerev.html
[KYK] index.html 수정
-홈 화면 예약 크기 수정
-홈 화면 캘린더 수정
=> [kyk] index.html 수정

eroom/src/main/resources/templates/index.html
=> [kyk] index.html

eroom/src/main/java/com/eroom/article/controller/ArticleController.java, eroom/src/main/java/com/eroom/mail/contorller/MailController.java, eroom/src/main/java/com/eroom/mail/entity/MailStatusMapping.java, eroom/src/main/java/com/eroom/mail/repository/MailStatusMappingRepository.java, eroom/src/main/java/com/eroom/mail/service/MailService.java, eroom/src/main/resources/templates/article/articleNotice.html, eroom/src/main/resources/templates/index.html, eroom/src/main/resources/templates/mail/mailCreate.html, eroom/src/main/resources/templates/mail/mailCreateDraft.html, eroom/src/main/resources/templates/mail/mailCreateReply.html, eroom/src/main/resources/templates/mail/mailDraft.html, eroom/src/main/resources/templates/mail/mailDraftUpdate.html, eroom/src/main/resources/templates/mail/mailImportant.html, eroom/src/main/resources/templates/mail/mailReceiverCc.html, eroom/src/main/resources/templates/mail/mailTrash.html
mail 카드
받은 메일 바로가기 아이콘
읽지 않은 메일/ 총 받은 메일 => 숫자로 처리
(웹소켓으로 비동기로 숫자 카운트)
=> Kty home 화면 mail 카드 작업

eroom/src/main/resources/templates/mail/mailReceiverTo.html, eroom/src/main/resources/templates/mail/mailSent.html
수정 위치 : mailReceiver.Html
-받은 메일 페이징 오류로 인해 받은 메일 안보이는 문제
-웹소켓 연결로 인해 초기화 코드 밖에 추가
=> Kty 받은 메일 페이지 오류 수정

eroom/src/main/java/com/eroom/news/controller/NewsController.java, eroom/src/main/resources/templates/index.html
=> [lyj] 뉴스API 수정

eroom/src/main/resources/templates/directory/treeModal.html
[ksk] 모달 트리구조 결과 확인 출력 수정_20250515
- 모달 트리구조 결과 확인 출력 수정
=> [ksk] 모달 트리구조 결과 확인 출력 수정_20250515

eroom/src/main/resources/templates/approval/agreementApprovals.html, eroom/src/main/resources/templates/approval/create.html, eroom/src/main/resources/templates/approval/fallBackApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/receivedApprovals.html, eroom/src/main/resources/templates/approval/referencedApprovals.html, eroom/src/main/resources/templates/directory/treeModal.html
- 트리 모달 결과 확인 출력 수정
- 트리 모달 체크박스 옆 빈 공간 누르면 최하위 요소 선택되는 오류 수정
=> [ksk] 트리 모달 결과 확인 출력 수정_20250515

eroom/src/main/java/com/eroom/reservation/controller/ReservationController.java, eroom/src/main/resources/templates/reservation/meetingroomrev.html
=> [kyk] 회의실 트리 구조 적용

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/resources/templates/chat/list.html
=> [lyj] 채팅 기능 수정

eroom/src/main/java/com/eroom/chat/controller/ChatController.java, eroom/src/main/resources/templates/chat/list.html
- 채팅방상세조회 참여자 css 수정
- 참여자추가하기 기존에 방에있는 인원 체크시 알림창
- 채팅방 만들기/참여자 추가하기 모달 생성/추가 시 더블클릭막음
- 채팅방 내용불러오기 innerHTML => 템플릿으로 교체
- 상세 누를시 오른쪽 채팅화면 다시업로드 되는거 고침
=> [lyj] 채팅방 기능 수정 

eroom/src/main/java/com/eroom/approval/service/ApprovalService.java, eroom/src/main/resources/templates/approval/create.html, eroom/src/main/resources/templates/approval/detail.html, eroom/src/main/resources/templates/directory/employeeList.html, eroom/src/main/resources/templates/directory/partnerList.html
[ksk] 트리 모달 결과 확인 출력 수정, alert 모달 적용 완료_20250515
- 트리 모달 결과 확인 출력 수정
- 트리 모달 체크박스 옆 빈 공간 누르면 최하위 요소 선택되는 오류 수정
- alert 모달, confirm 모달 적용 완료
- 회수 로직 수정(회수 버튼을 띄워두고 반려 받은 경우 예외처리)
- 수정용 unsaved 모달만 불러와뒀음.
- 결재 재기안시 결재자, 합의자, 참조자 모두 approver라는 이름을 갖고있던 오류 수정
=> [ksk] 트리 모달 결과 확인 출력 수정, alert 모달 적용 완료_20250515

eroom/src/main/resources/templates/article/articleCreate.html, eroom/src/main/resources/templates/article/articleDetail.html, eroom/src/main/resources/templates/article/articleEdit.html, eroom/src/main/resources/templates/article/articleNotice.html, eroom/src/main/resources/templates/mail/mailCreate.html, eroom/src/main/resources/templates/mail/mailCreateReply.html, eroom/src/main/resources/templates/mail/mailDetail.html, eroom/src/main/resources/templates/mail/mailDraft.html, eroom/src/main/resources/templates/mail/mailDraftUpdate.html, eroom/src/main/resources/templates/mail/mailImportant.html, eroom/src/main/resources/templates/mail/mailReceiverCc.html, eroom/src/main/resources/templates/mail/mailReceiverTo.html, eroom/src/main/resources/templates/mail/mailSent.html, eroom/src/main/resources/templates/mail/mailTrash.html, eroom/src/main/resources/templates/mail/test.html
메일
-메일 작성
-답장
-임시저장 수정
-휴지통 삭제, 복구 알람창 추가
게시판
-게시글 작성
-게시글 수정
-게시글 삭제 알람창 추가
=> Kty 모달 알람창 통일 ( 메일, 게시판 )

eroom/src/main/java/com/eroom/websocket/ApprovalWebSocketHandler.java, eroom/src/main/resources/templates/approval/detail.html, eroom/src/main/resources/templates/include/layout.html, eroom/src/main/resources/templates/index.html
[ksk] 결재 웹소켓 오류 수정_20250516
- 카드 크기 통일
- 결재 웹소켓 오류 수정
=> [ksk] 결재 웹소켓 오류 수정_20250516

eroom/src/main/java/com/eroom/home/controller/HomeController.java
- 카드 크기 통일
- 결재 웹소켓 오류 수정
- 메인페이지 결재 출력 개수 수정
=> [ksk] 메인페이지 결재 출력 개수 수정_20250516

eroom/src/main/java/com/eroom/attendance/service/AnnualLeaveService.java, eroom/src/main/java/com/eroom/employee/service/EmployeeService.java, eroom/src/main/java/com/eroom/mypage/controller/MyPageController.java, eroom/src/main/resources/templates/admin/employeeInfoView.html, eroom/src/main/resources/templates/mypage/list.html
- 마이페이지의 근태 현황 목록 비동기 방식으로 변경.
- 회원 생성시 연차 정보 (현재연도, 연차수: 0 으로 생성) 등록 처리
- 연차 수정시 현재 연도 기준 설정 -> 기준일 연차 수정으로 변경.
=> [cya] 마이페이지, 회원관리 페이지 수정

eroom/src/main/resources/templates/chat/list.html
- 채팅방 이름변경 완료후 모달끄기
- 채팅방 생성자는 나가기 X => 삭제만 가능
=> [lyj] 그룹채팅방 수정

eroom/src/main/java/com/eroom/chat/controller/ChatController.java
=> [lyj] 채팅방 목록 마지막메시지 순으로 정렬

eroom/src/main/resources/templates/chat/list.html, eroom/src/main/resources/templates/drive/company.html
=> [lyj] 채팅방 마지막 메시지 오류 고침

eroom/src/main/java/com/eroom/approval/controller/ApprovalPdfController.java, eroom/src/main/resources/templates/approval/agreementApprovals.html, eroom/src/main/resources/templates/approval/detail.html, eroom/src/main/resources/templates/approval/fallBackApprovals.html, eroom/src/main/resources/templates/approval/myRequestedApprovals.html, eroom/src/main/resources/templates/approval/receivedApprovals.html, eroom/src/main/resources/templates/approval/referencedApprovals.html
=> [ksk] 타이틀 추가 작업 완료
